"""update_host_id

Revision ID: 4ba9327dc611
Revises: faa27b48b9b3
Create Date: 2026-07-07 13:27:42.482142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4ba9327dc611'
down_revision: Union[str, Sequence[str], None] = 'faa27b48b9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host_devices', sa.Column('host_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_host_devices_machine_id'), table_name='host_devices')
    op.create_index(op.f('ix_host_devices_host_id'), 'host_devices', ['host_id'], unique=True)
    op.drop_column('host_devices', 'machine_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host_devices', sa.Column('machine_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_host_devices_host_id'), table_name='host_devices')
    op.create_index(op.f('ix_host_devices_machine_id'), 'host_devices', ['machine_id'], unique=True)
    op.drop_column('host_devices', 'host_id')
    # ### end Alembic commands ###
