"""add_metadata_tokens_created_at_messagerole

Revision ID: 61e9b85fa176
Revises: 06f6660ab7b0
Create Date: 2026-07-08 10:18:22.547011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "61e9b85fa176"
down_revision: Union[str, Sequence[str], None] = "06f6660ab7b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    messagerole_enum = postgresql.ENUM("ASSISTANT", "USER", "TOOL", name="messagerole")
    messagerole_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("chat_messages", sa.Column("tokens", sa.Integer(), nullable=True))
    op.add_column(
        "chat_messages",
        sa.Column("metadata_", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.alter_column(
        "chat_messages",
        "role",
        existing_type=sa.VARCHAR(),
        type_=messagerole_enum,
        existing_nullable=False,
        postgresql_using="role::messagerole",
    )
    op.add_column(
        "chat_sessions",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_sessions", "updated_at")
    op.alter_column(
        "chat_messages",
        "role",
        existing_type=sa.Enum("ASSISTANT", "USER", "TOOL", name="messagerole"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("chat_messages", "metadata_")
    op.drop_column("chat_messages", "tokens")

    messagerole_enum = postgresql.ENUM("ASSISTANT", "USER", "TOOL", name="messagerole")
    messagerole_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
