"""add_token_name_expiry

Revision ID: e4cae7de745c
Revises: 0d03d0a61715
Create Date: 2026-07-06 14:19:03.326940

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "e4cae7de745c"
down_revision: Union[str, Sequence[str], None] = "0d03d0a61715"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_tokens",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("auth_tokens", sa.Column("expires_at", sa.DateTime(), nullable=True))
    op.drop_column("auth_tokens", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_tokens",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("auth_tokens", "expires_at")
    op.drop_column("auth_tokens", "name")
    # ### end Alembic commands ###
